title: Holden Ford
description: A portfolio of Holden's stuff.
remote_theme: just-the-docs

url: https://holden-f.github.io/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
