title: Holden Ford
description: A portfolio of Holden's stuff.
theme: just-the-docs

url: https://holden-f.github.io/portfolio/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
